  name: Chocolatine

  on :
    push:
      branches-ignore:
        - "ga-ignore- *"

  env:
    EXECUTABLES:

  jobs:
    checking_coding_style:
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/epitech/coding-style-checker:latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Coding Style checker
          run: |
            check.sh $(pwd) $(pwd)
            while read Line; \
            do \
            ARG1=$(echo $Line | cut -d: -f1); \
            ARG2=$(echo $Line | cut -d: -f2); \
            ARG3=$(echo $Line | cut -d: -f3); \
            ARG4=$(echo $Line | cut -d: -f4); \
            echo "::error file=$ARG1, line=$ARG2:: $ARG3 $ARG4"; \
            done < coding-style-reports.log
            if [ -s coding-style-reports.log ]; then
              exit 1
            fi

    check_program_compilation:
      runs-on: ubuntu-latest
      container:
        image: epitechcontent/epitest-docker:latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Compile
          run: make
          timeout-minutes: 2
        - name: Clean useless files
          run: make clean
        - name: Check exe
          run: |
            IFS=','
            for value in $EXECUTABLES; do
              if [ -e $value ]; then
                exit 0
              else
                exit 1
              fi
            done

    push_to_mirror:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: pixta-dev/repository-mirroring-action@v1.1.1
          with:
            ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            target_repo_url: git@github.com:EpitechPromo2028/B-DOP-200-LYN-2-1-chocolatine-alexis.drago-beltran.git
