  name: Chocolatine

#on change pas ici on lui dit ce qu'ils doit ignorer
#en gros si on met cette commande il bypass les test

  on :
    push:
      branches-ignore:
        - "ga-ignore- *"

#il dois trouver les fichier binaires

  env:
    EXECUTABLES: "test"

#c'est quoi ton taff ?

  jobs:
    checking_coding_style:
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/epitech/coding-style-checker:latest #il va chopper l'immage du docker de la norme
      steps: #il fait ces test
        - name: Checkout
          uses: actions/checkout@v4
        - name: Coding Style checker
          run: |
            check.sh $(pwd) $(pwd)
            while read Line; \
            do \
            ARG1=$(echo $Line | cut -d: -f1); \
            ARG2=$(echo $Line | cut -d: -f2); \
            ARG3=$(echo $Line | cut -d: -f3); \
            ARG4=$(echo $Line | cut -d: -f4); \
            echo "::error file=$ARG1, line=$ARG2:: $ARG3 $ARG4"; \
            done < coding-style-reports.log
            if [ -s coding-style-reports.log ]; then
              exit 1
            fi

    check_program_compilation: #il regarde si le programe compile bien, finit les build error
      runs-on: ubuntu-latest
      container:
        image: epitechcontent/epitest-docker:latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Compile
          run: make
          timeout-minutes: 3
        - name: Clean useless files
          run: make clean
        - name: Check exe
          run: |
            IFS=','
            for value in $EXECUTABLES; do
              if [ -e $value ]; then
                exit 0
              else
                exit 1
              fi
            done

    ##run_tests:
      ##needs: check_program_compilation
      ##runs-on: ubuntu-latest
      ##container:
        ##image: epitechcontent/epitest-docker
      ##steps:
        ##- name: Checkout
         ## uses: actions/checkout@v4
        ##- name: Run unit tests
         ## run: make tests_run
         ## timeout-minutes: 2

    push_to_mirror:
      ##needs: run_tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        ##- uses: pixta-dev/repository-mirroring-action@v1
          ##with:
            ssh_private_key:
              $${{ secrets.SSH_KEYGEN }} #clé ssh pour push sur le repo tek
            target_repo_url:
              https://github.com/EpitechPromo2028/B-DOP-200-LYN-2-1-chocolatine-alexis.drago-beltran.git