  name: Chocolatine

  on :
    push:
      branches-ignore:
        - "ga-ignore- *"

  env:
    EXECUTABLES:

  jobs:
    checking_coding_style:
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/epitech/coding-style-checker:latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Coding Style checker
          run: |
            input=$(pwd)/coding-style-reports.log
            awk -F':' '{print "::error title="$3" coding style error,file="$1",line="$2"::"$4}' $input
            if [ -s $input ]; then
              exit 1
            fi

    check_program_compilation:
      runs-on: ubuntu-latest
      needs: checking_coding_style
      container:
        image: epitechcontent/epitest-docker:latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4 #vérif version
        - name: Is Make Woking #previous Compile
          run: make
          timeout-minutes: 2 #on baisse un 1 ct 2 avant on va voir si sa merde et si on peut gangner du temps d'execution
        - name: Clean useless files
          run: make clean
        - name: Check exe
          run: |
            while IFS= read -r line; do
              if [ ! -x "$line" ]; then
                echo "::error ::$line is not executable"
                exit 1
              fi
            done
    #check unit test
    push_to_mirror:
        runs-on: ubuntu-latest
        needs: check_program_compilation
        steps:
        - uses: actions/checkout@v4 #again version a vérifier
          with:
            fetch-depth: 0
        - uses: pixta-dev/repository-mirroring-action@v1.1.1 #verifier si tout est ok pour le miror c ce qui pose pb rn
          with:
            target_repo_url: git@github.com:EpitechPromo2028/B-DOP-200-LYN-2-1-chocolatine-alexis.drago-beltran.git
            ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }} #clef ssh pour le repo epitech

            # TODO :
            # voir si autre probléme
            # Voir avec Marin pour faire un truc pour les forbiden functions
            # Voir aussi pour les test unitaires, il serait temps d'en faire